version: '3.9'
services:
  api:
    build: ./apps/api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - ADMIN_EMAIL=admin@example.com
      - ADMIN_PASSWORD=Admin#2025
      - JWT_SECRET=dev-secret-change-me
  web:
    build: ./apps/web
    ports:
      - "8080:80"
    environment:
      - VITE_API_BASE=http://api:3000
    depends_on:
      - api
